# -*- coding: utf-8 -*-
"""name_zh 翻譯對照表 —— build_data.py 引入用。
kind: person=人名(含事件卡人名) / group=群體稱號 / quote=台詞技名擬聲詞
status: auto=機械去空格/繁體正字高信心 / high/medium/low=研究後信心度 / confirmed=使用者拍板 / draft=待確認
組合卡與純漢字無變化的名稱(如「宮兄弟」)本來就是合法中文，故不建表，
build_data.py 查無條目時 name_zh 留空字串，前端 fallback 顯示 name 即可。
2026-07-07: 全面將人名/事件名裡的日文新字體轉為繁體正字（沢→澤、国→國、黒→黑 等）。"""

NAME_ZH_ENTRIES = [
    {
        "jp": "\"助走\"は 翔陽の翼だね",
        "zh": "「助跑」是翔陽的翅膀呢",
        "kind": "quote",
        "status": "high",
        "note": "影山飛雄對日向翔陽名台詞",
    },
    {
        "jp": "\"指揮者\"が代われば \"音\"が変わる",
        "zh": "換了「指揮者」，「音色」就會改變",
        "kind": "quote",
        "status": "high",
        "note": "烏養繋心/漫畫48話",
    },
    {
        "jp": "1stテンポの同時多発位置差攻撃",
        "zh": "第一節奏的同步多點位差攻擊",
        "kind": "quote",
        "status": "medium",
        "note": "漫畫297話戰術用語",
    },
    {
        "jp": "—\"その瞬間\"が 有るか、 無いかだ",
        "zh": "差別就在於——有沒有「那一瞬間」",
        "kind": "quote",
        "status": "high",
        "note": "木兎光太郎/漫畫89話",
    },
    {
        "jp": "―俺達は血液だ",
        "zh": "我們就是血液",
        "kind": "quote",
        "status": "high",
        "note": "黒尾鉄朗/漫畫28話",
    },
    {
        "jp": "…それで お前は何をやっている？",
        "zh": "……所以，你現在在做什麼？",
        "kind": "quote",
        "status": "high",
        "note": "牛島若利/漫畫211話",
    },
    {
        "jp": "あんたブロック上手だよ",
        "zh": "你很會攔網喔",
        "kind": "quote",
        "status": "high",
        "note": "角名倫太郎/漫畫270話",
    },
    {
        "jp": "いつも通りでいい 俺に勝負させろ",
        "zh": "照平常來就好，讓我去決勝負",
        "kind": "quote",
        "status": "high",
        "note": "岩泉一/漫畫127話",
    },
    {
        "jp": "うちのスパイカーに 道を空けろ",
        "zh": "給我家攻擊手讓路",
        "kind": "quote",
        "status": "medium",
        "note": "白布賢二郎/烏野vs白鳥沢",
    },
    {
        "jp": "おれにバレーボール教えてくれて ありがとう",
        "zh": "謝謝你教我打排球",
        "kind": "quote",
        "status": "high",
        "note": "孤爪研磨/垃圾場的決戰",
    },
    {
        "jp": "お前達は 強いよ",
        "zh": "你們很強",
        "kind": "quote",
        "status": "high",
        "note": "烏養繋心/動畫2期23話",
    },
    {
        "jp": "がんばれ",
        "zh": "加油",
        "kind": "quote",
        "status": "high",
        "note": "通用應援語",
    },
    {
        "jp": "これが \"繋ぐ\"ということだ",
        "zh": "這就是所謂的「連繫」",
        "kind": "quote",
        "status": "medium",
        "note": "舞台劇引用原作台詞",
    },
    {
        "jp": "ただーし！",
        "zh": "忠——！",
        "kind": "quote",
        "status": "high",
        "note": "山口忠(やまぐち ただし)拉長音的喊名，同卡skill_zh已將同一句譯為「忠——！」，此處補上一致",
    },
    {
        "jp": "どや俺の仲間すごいやろって もっと言いたかったわ",
        "zh": "真想再多說幾次「怎樣，我的夥伴很厲害吧」",
        "kind": "quote",
        "status": "confirmed",
        "note": "北信介/稲荷崎vs烏野賽後",
    },
    {
        "jp": "どん ぴしゃり",
        "zh": "分毫不差！",
        "kind": "quote",
        "status": "confirmed",
        "note": "擬聲詞，宮兄弟速攻/漫畫253話，使用者定案",
    },
    {
        "jp": "オープン攻撃",
        "zh": "高球進攻",
        "kind": "quote",
        "status": "confirmed",
        "note": "使用者定案",
    },
    {
        "jp": "クソ かっけえええ…!!!",
        "zh": "可惡，太強了啊！！！",
        "kind": "quote",
        "status": "confirmed",
        "note": "查無明確出處，僅確認為バボカ卡名（白鳥沢）。かっけえええ=かっこいい拉長音口語，字面是稱讚帥/酷，非「強」；2026-07-07曾定案採直譯「太帥氣了吧」，2026-07-08使用者知悉語意落差後仍選擇改回「太強了啊」（口語化/個人偏好考量）。",
    },
    {
        "jp": "コートの中には情報がいっぱいだ",
        "zh": "球場裡到處都是情報",
        "kind": "quote",
        "status": "high",
        "note": "日向翔陽/宮城一年選拔合宿",
    },
    {
        "jp": "ジャンバル最高!!",
        "zh": "Jump慶典最棒了！！",
        "kind": "quote",
        "status": "medium",
        "note": "Jump Victory Carnival宣傳用語",
    },
    {
        "jp": "ド ン ッ",
        "zh": "咚！",
        "kind": "quote",
        "status": "high",
        "note": "擬聲詞",
    },
    {
        "jp": "ドンピシャ!!",
        "zh": "完全命中！！",
        "kind": "quote",
        "status": "high",
        "note": "慣用語",
    },
    {
        "jp": "バレーは!!! 常に上を向くスポーツだ",
        "zh": "排球是！！！永遠向上看的運動",
        "kind": "quote",
        "status": "confirmed",
        "note": "烏養繋心/動畫3期10話",
    },
    {
        "jp": "バンチ・リード・ブロック",
        "zh": "集中站位讀切式攔網",
        "kind": "quote",
        "status": "medium",
        "note": "通用排球術語/伊達工戰術",
    },
    {
        "jp": "ヒナガラス",
        "zh": "雛烏",
        "kind": "person",
        "status": "high",
        "note": "官方周邊(LINE貼圖)用語，烏野隊員雛鳥/菜鳥哏，語源見漫畫4卷武田比喻",
    },
    {
        "jp": "ブッ潰ス!!!",
        "zh": "打垮你！！！",
        "kind": "quote",
        "status": "low",
        "note": "查無明確出處，二口堅治關聯",
    },
    {
        "jp": "ブロード攻撃",
        "zh": "背後時間差攻擊",
        "kind": "quote",
        "status": "confirmed",
        "note": "使用者定案",
    },
    {
        "jp": "プレーは大分 おりこうさんよな",
        "zh": "你的打法倒是挺乖的嘛",
        "kind": "quote",
        "status": "high",
        "note": "宮侑/全日本ユース強化合宿",
    },
    {
        "jp": "中島 猛",
        "zh": "中島猛",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "丸山 一喜",
        "zh": "丸山一喜",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "二口 堅治",
        "zh": "二口堅治",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "五色 工",
        "zh": "五色工",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "京谷 賢太郎",
        "zh": "京谷賢太郎",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "今年は面白くなりそうだな",
        "zh": "今年看來會很有意思啊",
        "kind": "quote",
        "status": "low",
        "note": "查無明確出處，バボカ事件卡名",
    },
    {
        "jp": "今日 何をする？",
        "zh": "今天，你要做什麼？",
        "kind": "quote",
        "status": "high",
        "note": "章節標語/漫畫390話",
    },
    {
        "jp": "佐久早 聖臣",
        "zh": "佐久早聖臣",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "作並 浩輔",
        "zh": "作並浩輔",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "俺のサーブの邪魔すんなや この喧しブタ",
        "zh": "別妨礙我發球啦，你這吵死人的豬",
        "kind": "quote",
        "status": "high",
        "note": "宮侑心聲/春高烏野vs稲荷崎",
    },
    {
        "jp": "俺も思った☆",
        "zh": "我也是這麼想的☆",
        "kind": "quote",
        "status": "high",
        "note": "及川徹/第133話",
    },
    {
        "jp": "僕一人で勝とうなんて1mmも思ってません",
        "zh": "我可一毫米都沒想過要靠自己一個人贏",
        "kind": "quote",
        "status": "high",
        "note": "月島蛍/第298話",
    },
    {
        "jp": "優勝候補ってやつだ",
        "zh": "這就是所謂的奪冠熱門啊",
        "kind": "quote",
        "status": "medium",
        "note": "稲荷崎「優勝候補」設定",
    },
    {
        "jp": "入畑 伸照",
        "zh": "入畑伸照",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "全員があなたを見ていますよ",
        "zh": "所有人都在看著你喔",
        "kind": "quote",
        "status": "high",
        "note": "赤葦京治/第244話",
    },
    {
        "jp": "前のめりで行くぜ",
        "zh": "勇往直前地衝吧！",
        "kind": "quote",
        "status": "confirmed",
        "note": "西谷夕/第65話",
    },
    {
        "jp": "助けてもらう!!!",
        "zh": "我要找人幫忙！！！",
        "kind": "quote",
        "status": "high",
        "note": "西谷夕/第278話",
    },
    {
        "jp": "北 信介",
        "zh": "北信介",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "十和田 良樹",
        "zh": "十和田良樹",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "千鹿谷 栄吉",
        "zh": "千鹿谷栄吉",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "及川 徹",
        "zh": "及川徹",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "双子速攻 マイナス・テンポ \"裏\"!!!",
        "zh": "雙子速攻　負節奏「裏」！！！",
        "kind": "quote",
        "status": "high",
        "note": "宮兄弟稲荷崎戰280-281話變化技，動畫4期22話",
    },
    {
        "jp": "古森 元也",
        "zh": "古森元也",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "吹上 仁悟",
        "zh": "吹上仁悟",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "周りの上手さに引っ張られる",
        "zh": "被周遭高手的實力帶著往上提升",
        "kind": "quote",
        "status": "medium",
        "note": "影山飛雄相關/全日本ユース強化合宿",
    },
    {
        "jp": "国見 英",
        "zh": "國見英",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "国見・五色",
        "zh": "國見・五色",
        "kind": "person",
        "status": "auto",
        "note": "組合卡，日文新字體轉繁體正字",
    },
    {
        "jp": "夜久 衛輔",
        "zh": "夜久衛輔",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "大将 優",
        "zh": "大将優",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "大平 獅音",
        "zh": "大平獅音",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "大耳 練",
        "zh": "大耳練",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "大見 太郎",
        "zh": "大見太郎",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "天内 叶歌",
        "zh": "天内叶歌",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "天童 覚",
        "zh": "天童覺",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "女川 太郎",
        "zh": "女川太郎",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "孤爪 研磨",
        "zh": "孤爪研磨",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "孤爪・黒尾",
        "zh": "孤爪・黑尾",
        "kind": "person",
        "status": "auto",
        "note": "組合卡，日文新字體轉繁體正字",
    },
    {
        "jp": "宮 侑",
        "zh": "宮侑",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "宮 治",
        "zh": "宮治",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "寒河江 勇将",
        "zh": "寒河江勇将",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "寺泊 基希",
        "zh": "寺泊基希",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "小作 裕渡",
        "zh": "小作裕渡",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "小原 豊",
        "zh": "小原豐",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "小見 春樹",
        "zh": "小見春樹",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "小鹿野 大樹",
        "zh": "小鹿野大樹",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "尾白 アラン",
        "zh": "尾白阿蘭",
        "kind": "person",
        "status": "medium",
        "note": "稲荷崎三年級WS背號4，羅馬字為Aran非Allen",
    },
    {
        "jp": "尾長 渉",
        "zh": "尾長渉",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "山口 忠",
        "zh": "山口忠",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "山形 隼人",
        "zh": "山形隼人",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "山本 あかね",
        "zh": "山本茜",
        "kind": "person",
        "status": "high",
        "note": "あかね常用漢字即茜",
    },
    {
        "jp": "山本 あかね・灰羽 アリサ",
        "zh": "山本茜・灰羽愛麗莎",
        "kind": "person",
        "status": "medium",
        "note": "上兩位合併卡",
    },
    {
        "jp": "山本 猛虎",
        "zh": "山本猛虎",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "山架 美華",
        "zh": "山架美華",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "岩泉 一",
        "zh": "岩泉一",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "嶋田 誠",
        "zh": "嶋田誠",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "川西 太一",
        "zh": "川西太一",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "強羅 昌己",
        "zh": "強羅昌己",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "影山 飛雄",
        "zh": "影山飛雄",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "影山というセッターの居ないお前に 俺は価値を感じない",
        "zh": "沒有影山這個舉球員的你，我感受不到價值",
        "kind": "quote",
        "status": "high",
        "note": "鷲匠鍛治對日向/宮城一年選拔合宿",
    },
    {
        "jp": "志賀 智也",
        "zh": "志賀智也",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "成田 一仁",
        "zh": "成田一仁",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "手は前っつったでしょ ノブカツくん",
        "zh": "我不是說過，手要往前伸嗎？『不過是社團』君",
        "kind": "quote",
        "status": "confirmed",
        "note": "黒尾鉄朗對月島蛍說，漫畫297話「師弟」（垃圾場的決戰）。ノブカツ非本名，是黑尾/木兎把月島口頭禪「ただの部活」（只是社團活動）諧音接成假人名「タダ・ノブカツ」的哏，用來酸他先前輕視排球的態度。2026-07-07使用者選定意譯版本以保留酸點，捨棄音譯「信勝君」與純用本名「月島君」兩案。",
    },
    {
        "jp": "手白 球彦",
        "zh": "手白球彦",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "探せ",
        "zh": "找出來！",
        "kind": "quote",
        "status": "confirmed",
        "note": "查無明確出處",
    },
    {
        "jp": "斉藤 明",
        "zh": "斉藤明",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "日向 夏",
        "zh": "日向夏",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "日向 翔陽",
        "zh": "日向翔陽",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "日向・百沢",
        "zh": "日向・百澤",
        "kind": "person",
        "status": "auto",
        "note": "組合卡，日文新字體轉繁體正字",
    },
    {
        "jp": "日向・黄金川",
        "zh": "日向・黃金川",
        "kind": "person",
        "status": "auto",
        "note": "組合卡，日文新字體轉繁體正字",
    },
    {
        "jp": "星海 光来",
        "zh": "星海光來",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "昼神 幸郎",
        "zh": "晝神幸郎",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "最強の防御で最速の攻撃 それが \"ブロック\"。",
        "zh": "最強的防守，也是最快的攻擊——那就是「攔網」",
        "kind": "quote",
        "status": "medium",
        "note": "通用攔網解說術語",
    },
    {
        "jp": "月島 蛍",
        "zh": "月島螢",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "月島・黒尾",
        "zh": "月島・黑尾",
        "kind": "person",
        "status": "auto",
        "note": "組合卡，日文新字體轉繁體正字",
    },
    {
        "jp": "期待してる",
        "zh": "我期待你的表現",
        "kind": "quote",
        "status": "low",
        "note": "查無明確出處，早期バボカ卡名",
    },
    {
        "jp": "木下 久志",
        "zh": "木下久志",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "木兎 光太郎",
        "zh": "木兎光太郎",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "木葉 秋紀",
        "zh": "木葉秋紀",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "来年の\"鉄壁\"は 絶対崩れねぇよ",
        "zh": "明年的「鐵壁」，絕對不會被擊潰",
        "kind": "quote",
        "status": "high",
        "note": "茂庭要/漫畫6卷伊達工戰後",
    },
    {
        "jp": "東峰 旭",
        "zh": "東峰旭",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "松川 一静",
        "zh": "松川一静",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "楽してこうぜ 百沢ァー!!",
        "zh": "別繃得那麼緊啦，百澤——！！",
        "kind": "quote",
        "status": "confirmed",
        "note": "日向翔陽對百沢雄大/動畫4期4話",
    },
    {
        "jp": "武田 一鉄",
        "zh": "武田一鐵",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "池尻 隼人",
        "zh": "池尻隼人",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "沼井 和馬",
        "zh": "沼井和馬",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "海 信行",
        "zh": "海信行",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "清水 潔子",
        "zh": "清水潔子",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "渡 親治",
        "zh": "渡親治",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "滑津 舞",
        "zh": "滑津舞",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "滝ノ上 祐輔",
        "zh": "滝之上祐輔",
        "kind": "person",
        "status": "draft",
        "note": "ノ→之；滝/瀧用字待確認，暫不轉繁體",
    },
    {
        "jp": "潜 尚保",
        "zh": "潜尚保",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "澤村 大地",
        "zh": "澤村大地",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "澤村・黒尾",
        "zh": "澤村・黑尾",
        "kind": "person",
        "status": "auto",
        "note": "組合卡，日文新字體轉繁體正字",
    },
    {
        "jp": "瀬見 英太",
        "zh": "瀨見英太",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "火焼 呼太郎",
        "zh": "火焼呼太郎",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "灰羽 アリサ",
        "zh": "灰羽愛麗莎",
        "kind": "person",
        "status": "medium",
        "note": "列夫姊姊，英文圈作Alisa，取俄語感與弟弟列夫一致",
    },
    {
        "jp": "灰羽 リエーフ",
        "zh": "灰羽列夫",
        "kind": "person",
        "status": "high",
        "note": "音駒一年MB，日俄混血，名字源自俄語Lev(獅子)，比照托爾斯泰譯法",
    },
    {
        "jp": "烏養 一繋",
        "zh": "烏養一繋",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "烏養 繋心",
        "zh": "烏養繋心",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "照島 遊児",
        "zh": "照島遊兒",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "牛島 若利",
        "zh": "牛島若利",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "物理攻撃でブン殴ればいい だよね",
        "zh": "用物理攻擊狠狠揍下去就好，對吧",
        "kind": "quote",
        "status": "high",
        "note": "孤爪研磨的遊戲式比喻/漫畫36卷",
    },
    {
        "jp": "犬岡 走",
        "zh": "犬岡走",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "猫又 育史",
        "zh": "猫又育史",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "猿杙 大和",
        "zh": "猿杙大和",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "理石 平介",
        "zh": "理石平介",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "田中 冴子",
        "zh": "田中冴子",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "田中 龍之介",
        "zh": "田中龍之介",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "田代 秀水",
        "zh": "田代秀水",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "由良 正太",
        "zh": "由良正太",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "白峰 周",
        "zh": "白峰周",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "白布 賢二郎",
        "zh": "白布賢二郎",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "白布・瀬見",
        "zh": "白布・瀨見",
        "kind": "person",
        "status": "auto",
        "note": "組合卡，日文新字體轉繁體正字",
    },
    {
        "jp": "百沢 雄大",
        "zh": "百澤雄大",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "着地上手組。",
        "zh": "落地高手組。",
        "kind": "person",
        "status": "high",
        "note": "官方特裝版書籍頁確認為日向翔陽+西谷夕雙人卡HV-PR-057，非原作台詞，此卡實為CHARACTER分類",
    },
    {
        "jp": "矢巾 秀",
        "zh": "矢巾秀",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "福永 招平",
        "zh": "福永招平",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "稲荷崎応援団",
        "zh": "稻荷崎應援團",
        "kind": "person",
        "status": "draft",
        "note": "比照school名稱稲荷崎→稻荷崎慣例，可override",
    },
    {
        "jp": "穴原 孝昭",
        "zh": "穴原孝昭",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "笹谷 武仁",
        "zh": "笹谷武仁",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "絶望の継続や",
        "zh": "讓絕望延續吧",
        "kind": "quote",
        "status": "confirmed",
        "note": "查無明確出處，北信介相關バボカ卡名",
    },
    {
        "jp": "縁下 力",
        "zh": "縁下力",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "芝山 優生",
        "zh": "芝山優生",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "花巻 貴大",
        "zh": "花巻貴大",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "若利君を倒したければ俺を倒してから行け～ ってな～",
        "zh": "想打倒若利君，就先過我這關～之類的啦～",
        "kind": "quote",
        "status": "high",
        "note": "天童覚/第155話",
    },
    {
        "jp": "茂庭 要",
        "zh": "茂庭要",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "菅原 孝支",
        "zh": "菅原孝支",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "西谷 夕",
        "zh": "西谷夕",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "角名 倫太郎",
        "zh": "角名倫太郎",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "誰だろうと受けて立つ",
        "zh": "無論是誰，我都接受挑戰",
        "kind": "quote",
        "status": "medium",
        "note": "",
    },
    {
        "jp": "護りの音駒でリベロやるって チョー名誉だろ",
        "zh": "能在防守聞名的音駒當自由球員，是最大的榮譽吧！",
        "kind": "quote",
        "status": "confirmed",
        "note": "查無明確出處，疑為夜久相關",
    },
    {
        "jp": "谷地 仁花",
        "zh": "谷地仁花",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "赤倉 櫂",
        "zh": "赤倉櫂",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "赤木 路成",
        "zh": "赤木路成",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "赤葦 京治",
        "zh": "赤葦京治",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "超インナークロス!!!",
        "zh": "超銳角斜線扣球！！！",
        "kind": "quote",
        "status": "medium",
        "note": "田中龍之介相關招式/春高烏野vs稲荷崎",
    },
    {
        "jp": "越後 栄",
        "zh": "越後栄",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "追分 拓朗",
        "zh": "追分拓朗",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "金沢 伊織",
        "zh": "金澤伊織",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "金田一 勇太郎",
        "zh": "金田一勇太郎",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "金田一・国見",
        "zh": "金田一・國見",
        "kind": "person",
        "status": "auto",
        "note": "組合卡，日文新字體轉繁體正字",
    },
    {
        "jp": "銀島 結",
        "zh": "銀島結",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "鎌先 靖志",
        "zh": "鎌先靖志",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "長松 夢人",
        "zh": "長松夢人",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "闇路 建行",
        "zh": "闇路建行",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "雲雀田 吹",
        "zh": "雲雀田吹",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "青根 高伸",
        "zh": "青根高伸",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "音駒の専売特許じゃねえぞォ！",
        "zh": "這可不是音駒的專利啊！",
        "kind": "quote",
        "status": "low",
        "note": "查無明確出處，梟谷事件卡",
    },
    {
        "jp": "頼むぞ",
        "zh": "拜託了",
        "kind": "quote",
        "status": "high",
        "note": "通用短句",
    },
    {
        "jp": "鬼と 鬼だな",
        "zh": "是鬼與鬼呢",
        "kind": "quote",
        "status": "confirmed",
        "note": "猫又育史/動畫1期13話",
    },
    {
        "jp": "鷲匠 鍛治",
        "zh": "鷲匠鍛治",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "鷲尾 辰生",
        "zh": "鷲尾辰生",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "黄金川 貫至",
        "zh": "黃金川貫至",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "黒尾 鉄朗",
        "zh": "黑尾鐵朗",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "黒尾・山本",
        "zh": "黑尾・山本",
        "kind": "person",
        "status": "auto",
        "note": "組合卡，日文新字體轉繁體正字",
    },
    {
        "jp": "黒川 広樹",
        "zh": "黑川廣樹",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "黒石 純二",
        "zh": "黑石純二",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
    {
        "jp": "黒須 法宗",
        "zh": "黑須法宗",
        "kind": "person",
        "status": "auto",
        "note": "",
    },
]
