// Auto-generated by fetch_news.js — 手動欄位（desc/img）會被保留
const PROMO_NEWS = {
  items: [
    {
      date: '2026-10-24',
      title: 'HV-P04 ハイキュー!! バボカ!! BREAK ブースターパック 才能とセンス',
      desc: '',
      link: 'https://www.takaratomy.co.jp/products/haikyuvobacabreak/product/HV-P04.html',
      img: 'https://www.takaratomy.co.jp/products/haikyuvobacabreak/img/mv7/ttl.webp',
      productCode: 'HV-P04',
      productType: 'ブースターパック',
    },
    {
      date: '2026-06-27',
      title: 'HV-P03 ハイキュー!! バボカ!! BREAK ブースターパック ユース&選抜強化合宿',
      desc: '',
      link: 'https://www.takaratomy.co.jp/products/haikyuvobacabreak/product/HV-P03.html',
      img: 'https://www.takaratomy.co.jp/products/haikyuvobacabreak/img/mv6/ttl.webp',
      productCode: 'HV-P03',
      productType: 'ブースターパック',
    },
    {
      date: '2026-02-28',
      title: 'HV-P02 ハイキュー!! バボカ!! BREAK ブースターパック 最強の挑戦者',
      desc: '',
      link: 'https://www.takaratomy.co.jp/products/haikyuvobacabreak/product/HV-P02.html',
      img: 'https://www.takaratomy.co.jp/products/haikyuvobacabreak/img/mv4/ttl.webp',
      productCode: 'HV-P02',
      productType: 'ブースターパック',
    },
    {
      date: '2026-02-28',
      title: 'HV-D03 ハイキュー!! バボカ!! BREAK スターターデッキ 稲荷崎高校',
      desc: '',
      link: 'https://www.takaratomy.co.jp/products/haikyuvobacabreak/product/HV-D03.html',
      img: 'https://www.takaratomy.co.jp/products/haikyuvobacabreak/img/mv5/ttl.webp',
      productCode: 'HV-D03',
      productType: 'スターターデッキ',
    },
    {
      date: '2025-10-25',
      title: 'HV-P01 ハイキュー!! バボカ!! BREAK ブースターパック ゴミ捨て場の決戦',
      desc: '',
      link: 'https://www.takaratomy.co.jp/products/haikyuvobacabreak/product/HV-P01.html',
      img: '',
      productCode: 'HV-P01',
      productType: 'ブースターパック',
    },
    {
      date: '',
      title: 'HV-D04 ハイキュー!! バボカ!! BREAK スターターデッキ 青葉城西高校',
      desc: '',
      link: 'https://www.takaratomy.co.jp/products/haikyuvobacabreak/product/HV-D04.html',
      img: 'https://www.takaratomy.co.jp/products/haikyuvobacabreak/img/mv8/ttl.webp',
      productCode: 'HV-D04',
      productType: 'スターターデッキ',
    }
  ],
};
